Repository Clover-Habiters/backend, pull requests merged in 2023-07, with the labels that each got.

#9 [#6] Feat: Bookmark 기능 추가
  src/main/java/com/clover/habbittracker/domain/bookmark/api/BookMarkController.java
  src/main/java/com/clover/habbittracker/domain/bookmark/api/BookmarkController.java
  src/main/java/com/clover/habbittracker/domain/bookmark/dto/BookmarkResponse.java
  src/main/java/com/clover/habbittracker/domain/bookmark/dto/CreateBookmarkRequest.java
  src/main/java/com/clover/habbittracker/domain/bookmark/entity/BookMark.java
  src/main/java/com/clover/habbittracker/domain/bookmark/entity/Bookmark.java
  src/main/java/com/clover/habbittracker/domain/bookmark/repository/BookMarkRepository.java
  src/main/java/com/clover/habbittracker/domain/bookmark/repository/BookmarkCustomRepository.java
  src/main/java/com/clover/habbittracker/domain/bookmark/repository/BookmarkCustomRepositoryImpl.java
  src/main/java/com/clover/habbittracker/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/clover/habbittracker/domain/bookmark/service/BookMarkService.java
  src/main/java/com/clover/habbittracker/domain/bookmark/service/BookmarkService.java
  src/main/java/com/clover/habbittracker/domain/comment/entity/Comment.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostSimpleResponse.java
  src/main/resources/schema.sql
Labels: ✨ Feature, 📬 API, 📋 Habitimunity

#12 [#11] Feat: Redis 추가
  build.gradle
  src/main/java/com/clover/habbittracker/global/config/RedisConfig.java
Labels: ⚙ Setting

#13 [#11] Feat: Redis 설정 추가
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/clover/habbittracker/global/config/RedisConfig.java
  src/main/resources/application.yml
  src/test/java/com/clover/habbittracker/global/config/EmbeddedRedisConfig.java
  src/test/resources/application.yml
Labels: ⚙ Setting

#10 [#4] Fix : Post API 코드 수정
  build.gradle
  src/main/java/com/clover/habbittracker/domain/comment/dto/CommentResponse.java
  src/main/java/com/clover/habbittracker/domain/post/api/PostController.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostDetailResponse.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostRequest.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostResponse.java
  src/main/java/com/clover/habbittracker/domain/post/entity/Post.java
  src/main/java/com/clover/habbittracker/domain/post/mapper/PostMapper.java
  src/main/java/com/clover/habbittracker/domain/post/service/PostServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#15 [#5] Feat: Emoji 기능 추가
  .docker/Dockerfile
  .docker/docker-compose.yml
  .github/workflows/CD-Deploy.yml
  nginx.conf
  src/main/java/com/clover/habbittracker/domain/comment/entity/Comment.java
  src/main/java/com/clover/habbittracker/domain/emoji/api/EmojiController.java
  src/main/java/com/clover/habbittracker/domain/emoji/entity/Emoji.java
  src/main/java/com/clover/habbittracker/domain/emoji/repository/EmojiCustomRepository.java
  src/main/java/com/clover/habbittracker/domain/emoji/repository/EmojiCustomRepositoryImpl.java
  src/main/java/com/clover/habbittracker/domain/emoji/repository/EmojiRepository.java
  src/main/java/com/clover/habbittracker/domain/emoji/service/EmojiService.java
  src/main/java/com/clover/habbittracker/domain/like/api/LikeController.java
  src/main/java/com/clover/habbittracker/domain/like/entity/Like.java
  src/main/java/com/clover/habbittracker/domain/like/entity/Type.java
  src/main/java/com/clover/habbittracker/domain/like/repository/LikeRepository.java
  src/main/java/com/clover/habbittracker/domain/like/service/LikeService.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostDetailResponse.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostResponse.java
  src/main/java/com/clover/habbittracker/domain/post/entity/Post.java
  src/main/java/com/clover/habbittracker/domain/post/mapper/PostMapper.java
  src/main/resources/schema.sql
Labels: ✨ Feature, 📬 API, 📋 Habitimunity

#17 Feat : 댓글 API 기능 구현
  src/main/java/com/clover/habbittracker/domain/comment/api/CommentController.java
  src/main/java/com/clover/habbittracker/domain/comment/dto/CommentRequest.java
  src/main/java/com/clover/habbittracker/domain/comment/dto/CommentResponse.java
  src/main/java/com/clover/habbittracker/domain/comment/entity/Comment.java
  src/main/java/com/clover/habbittracker/domain/comment/mapper/CommentMapper.java
  src/main/java/com/clover/habbittracker/domain/comment/repository/CommentCustomRepository.java
  src/main/java/com/clover/habbittracker/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/com/clover/habbittracker/domain/comment/repository/CommentRepository.java
  src/main/java/com/clover/habbittracker/domain/comment/service/CommentService.java
  src/main/java/com/clover/habbittracker/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/clover/habbittracker/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/resources/schema.sql
  src/test/java/com/clover/habbittracker/domain/bookmark/api/BookmarkControllerTest.java
  src/test/java/com/clover/habbittracker/domain/bookmark/repository/BookmarkRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/bookmark/service/BookmarkServiceTest.java
  src/test/java/com/clover/habbittracker/domain/comment/api/CommentControllerTest.java
  src/test/java/com/clover/habbittracker/domain/comment/entity/CommentTest.java
  src/test/java/com/clover/habbittracker/domain/comment/mapper/CommentMapperTest.java
  src/test/java/com/clover/habbittracker/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/comment/service/CommentServiceTest.java
  src/test/java/com/clover/habbittracker/global/util/MemberProvider.java
  src/test/java/com/clover/habbittracker/global/util/PostProvider.java
Labels: ✨ Feature, 📬 API, 📋 Habitimunity

#19 Chore: 패키지 구조 변경
  build/generated/sources/annotationProcessor/java/main/com/clover/habbittracker/global/base/entity/QBaseEntity.java
  src/main/java/com/clover/habbittracker/domain/bookmark/entity/Bookmark.java
  src/main/java/com/clover/habbittracker/domain/comment/api/CommentController.java
  src/main/java/com/clover/habbittracker/domain/comment/entity/Comment.java
  src/main/java/com/clover/habbittracker/domain/diary/api/DiaryController.java
  src/main/java/com/clover/habbittracker/domain/diary/entity/Diary.java
  src/main/java/com/clover/habbittracker/domain/emoji/entity/Emoji.java
  src/main/java/com/clover/habbittracker/domain/habit/api/HabitController.java
  src/main/java/com/clover/habbittracker/domain/habit/entity/Habit.java
  src/main/java/com/clover/habbittracker/domain/habitcheck/entity/HabitCheck.java
  src/main/java/com/clover/habbittracker/domain/member/api/MemberController.java
  src/main/java/com/clover/habbittracker/domain/member/entity/Member.java
  src/main/java/com/clover/habbittracker/domain/post/api/PostController.java
  src/main/java/com/clover/habbittracker/domain/post/entity/Post.java
  src/main/java/com/clover/habbittracker/global/base/dto/ApiResponse.java
  src/main/java/com/clover/habbittracker/global/base/dto/BaseResponse.java
  src/main/java/com/clover/habbittracker/global/base/dto/ErrorResponse.java
  src/main/java/com/clover/habbittracker/global/base/dto/ResponseType.java
  src/main/java/com/clover/habbittracker/global/base/dto/ResultCode.java
  src/main/java/com/clover/habbittracker/global/base/entity/BaseEntity.java
  src/main/java/com/clover/habbittracker/global/exception/GlobalExceptionHandler.java
  src/main/java/com/clover/habbittracker/global/infra/ObjectStorageService.java
  src/main/java/com/clover/habbittracker/global/infra/config/NcpConfig.java
  src/test/java/com/clover/habbittracker/infra/ObjectStorageServiceTest.java
Labels: 🔨 Refactor

#22 [#21] Feat: 검색 기능 구현
  .github/workflows/CD-Deploy.yml
  .github/workflows/CI.yml
  build.gradle
  src/main/java/com/clover/habbittracker/domain/post/api/PostController.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostDetailResponse.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostRequest.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostResponse.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostSearchCondition.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostSimpleResponse.java
  src/main/java/com/clover/habbittracker/domain/post/entity/Category.java
  src/main/java/com/clover/habbittracker/domain/post/entity/Post.java
  src/main/java/com/clover/habbittracker/domain/post/repository/PostCustomRepository.java
  src/main/java/com/clover/habbittracker/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/clover/habbittracker/domain/post/service/PostService.java
  src/main/java/com/clover/habbittracker/domain/post/service/PostServiceImpl.java
  src/main/java/com/clover/habbittracker/global/config/db/JpaConfig.java
  src/main/java/com/clover/habbittracker/global/config/db/MySQLConfig.java
  src/main/java/com/clover/habbittracker/global/config/db/RedisConfig.java
  src/main/java/com/clover/habbittracker/global/config/web/WebConfig.java
  src/main/java/com/clover/habbittracker/global/exception/GlobalExceptionHandler.java
  src/main/java/com/clover/habbittracker/global/log/MyLogger.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/test/java/com/clover/habbittracker/domain/bookmark/repository/BookmarkRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/diary/repository/DiaryRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/habit/api/HabitControllerTest.java
  src/test/java/com/clover/habbittracker/domain/habit/repository/HabitRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/habitCheck/repository/HabitCheckRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/clover/habbittracker/global/util/PostProvider.java
  src/test/resources/application.yml
Labels: 📬 API, 📋 Habitimunity

#20 [#18] Refector : 소셜 로그인 리팩터링
  src/main/java/com/clover/habbittracker/domain/member/service/MemberService.java
  src/main/java/com/clover/habbittracker/domain/member/service/MemberServiceImpl.java
  src/main/java/com/clover/habbittracker/global/security/config/SecurityConfig.java
  src/main/java/com/clover/habbittracker/global/security/oauth/OauthProvider.java
  src/main/java/com/clover/habbittracker/global/security/oauth/OauthService.java
  src/main/java/com/clover/habbittracker/global/security/oauth/Social.java
  src/main/java/com/clover/habbittracker/global/security/oauth/dto/GoogleUser.java
  src/main/java/com/clover/habbittracker/global/security/oauth/dto/KakaoUser.java
  src/main/java/com/clover/habbittracker/global/security/oauth/dto/NaverUser.java
  src/main/java/com/clover/habbittracker/global/security/oauth/dto/SocialUser.java
  src/main/java/com/clover/habbittracker/global/security/oauth/handler/OAuthFailureHandler.java
  src/main/java/com/clover/habbittracker/global/security/oauth/handler/OauthSuccessHandler.java
  src/main/java/com/clover/habbittracker/global/security/oauth/repository/HttpCookieOAuthAuthorizationRequestRepository.java
  src/main/java/com/clover/habbittracker/global/security/oauth/service/OauthService.java
  src/main/resources/application-security.yml
  src/test/java/com/clover/habbittracker/domain/member/service/MemberServiceTest.java
  src/test/java/com/clover/habbittracker/global/security/oauth/SocialTest.java
  src/test/java/com/clover/habbittracker/global/security/oauth/service/OauthServiceTest.java
  src/test/java/com/clover/habbittracker/global/security/oauth/util/OauthUserProvider.java
Labels: 🔨 Refactor

#27 [#4] Post 테스트 코드 추가
  src/main/java/com/clover/habbittracker/domain/post/api/PostController.java
  src/main/java/com/clover/habbittracker/domain/post/repository/PostCustomRepository.java
  src/main/java/com/clover/habbittracker/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/com/clover/habbittracker/domain/post/service/PostService.java
  src/main/java/com/clover/habbittracker/domain/post/service/PostServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/clover/habbittracker/domain/post/mapper/PostMapperTest.java
  src/test/java/com/clover/habbittracker/domain/post/repository/PostRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/post/service/PostServiceTest.java
  src/test/java/com/clover/habbittracker/global/util/PostProvider.java
  src/test/resources/application.yml
  src/test/resources/searchTest_after.sql
Labels: 🔨 Refactor, 📋 Habitimunity

#30 [#5] Emoji 리팩터링 및 테스트 코드 추가
  src/main/java/com/clover/habbittracker/domain/comment/dto/CommentResponse.java
  src/main/java/com/clover/habbittracker/domain/diary/dto/DiaryResponse.java
  src/main/java/com/clover/habbittracker/domain/emoji/api/EmojiController.java
  src/main/java/com/clover/habbittracker/domain/emoji/dto/EmojiResponse.java
  src/main/java/com/clover/habbittracker/domain/emoji/entity/Emoji.java
  src/main/java/com/clover/habbittracker/domain/emoji/mapper/EmojiMapper.java
  src/main/java/com/clover/habbittracker/domain/emoji/repository/EmojiCustomRepository.java
  src/main/java/com/clover/habbittracker/domain/emoji/repository/EmojiCustomRepositoryImpl.java
  src/main/java/com/clover/habbittracker/domain/emoji/repository/EmojiRepository.java
  src/main/java/com/clover/habbittracker/domain/emoji/service/EmojiService.java
  src/main/java/com/clover/habbittracker/domain/habit/dto/HabitResponse.java
  src/main/java/com/clover/habbittracker/domain/habit/dto/MyHabitResponse.java
  src/main/java/com/clover/habbittracker/domain/habitcheck/dto/HabitCheckResponse.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostDetailResponse.java
  src/main/java/com/clover/habbittracker/domain/post/dto/PostResponse.java
  src/main/java/com/clover/habbittracker/domain/post/entity/Post.java
  src/main/java/com/clover/habbittracker/global/config/web/WebConfig.java
  src/main/resources/schema.sql
  src/test/java/com/clover/habbittracker/HabitTrackerApplicationTests.java
  src/test/java/com/clover/habbittracker/base/ControllerTest.java
  src/test/java/com/clover/habbittracker/base/RepositoryTest.java
  src/test/java/com/clover/habbittracker/base/ServiceTest.java
  src/test/java/com/clover/habbittracker/config/EmbeddedRedisConfig.java
  src/test/java/com/clover/habbittracker/domain/bookmark/api/BookmarkControllerTest.java
  src/test/java/com/clover/habbittracker/domain/bookmark/entity/BookmarkTest.java
  src/test/java/com/clover/habbittracker/domain/bookmark/repository/BookmarkRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/bookmark/service/BookmarkServiceTest.java
  src/test/java/com/clover/habbittracker/domain/comment/api/CommentControllerTest.java
  src/test/java/com/clover/habbittracker/domain/comment/mapper/CommentMapperTest.java
  src/test/java/com/clover/habbittracker/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/comment/service/CommentServiceTest.java
  src/test/java/com/clover/habbittracker/domain/diary/api/DiaryControllerTest.java
  src/test/java/com/clover/habbittracker/domain/diary/repository/DiaryRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/diary/service/DiaryServiceTest.java
  src/test/java/com/clover/habbittracker/domain/emoji/api/EmojiControllerTest.java
  src/test/java/com/clover/habbittracker/domain/emoji/entity/EmojiTest.java
  src/test/java/com/clover/habbittracker/domain/emoji/repository/EmojiCustomRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/emoji/service/EmojiServiceTest.java
  src/test/java/com/clover/habbittracker/domain/habit/api/HabitControllerTest.java
  src/test/java/com/clover/habbittracker/domain/habit/repository/HabitRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/habit/service/HabitServiceTest.java
  src/test/java/com/clover/habbittracker/domain/member/api/MemberControllerTest.java
  src/test/java/com/clover/habbittracker/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/member/service/MemberServiceTest.java
  src/test/java/com/clover/habbittracker/domain/post/mapper/PostMapperTest.java
  src/test/java/com/clover/habbittracker/domain/post/repository/PostRepositoryTest.java
  src/test/java/com/clover/habbittracker/domain/post/service/PostServiceTest.java
  src/test/java/com/clover/habbittracker/global/infra/ObjectStorageServiceTest.java
  src/test/java/com/clover/habbittracker/global/security/oauth/service/OauthServiceTest.java
  src/test/java/com/clover/habbittracker/util/ApiDocumentUtils.java
  src/test/java/com/clover/habbittracker/util/CommentProvider.java
  src/test/java/com/clover/habbittracker/util/EmojiProvider.java
  src/test/java/com/clover/habbittracker/util/MemberProvider.java
  src/test/java/com/clover/habbittracker/util/PostProvider.java
Labels: ✨ Feature, 📬 API, 📋 Habitimunity
